[app]
APP_DEBUG = true
APP_CORS = true
APP_PORT = 5000

[jwt]
ACCESS_TOKEN_EXPIRE_TIME = 30                 # 30s
REFRESH_TOKEN_EXPIRE_TIME = 604800            # 7 days
ACCESS_TOKEN_SECRET = "access-token-secret"
REFRESH_TOKEN_SECRET = "refresh-token-secret"

[database]
DB_URL = "sqlite+aiosqlite:///database.db"
